### ISSUE TITLE
need more annotated intomation from vcf input

### ISSUE THREAD

**Issue by die4live** [zwdzwd/transvar#13]
There are very simple annotation info when use vcf as input currently, as for `ganno`: no cDNA and protein mutation info in column 'coordinates', also no detail region info but only position between which telomere in column 'region'.

and seems `canno`/`panno` does not support `--vcf` but this arg is listed in command help info.

would it be possible to provide more info for vcf input, thanks!

**Comment by zwdzwd** [comment]
There should be cDNA and protein mutation info if you supply transcript database correctly. Based on my experience the 'telomere' info is usually seen when the transcript database is missing (so transvar would see it as merely between the two telomeres). 

yes, vcf is not that relevant for canno and panno (since they are not typically stored in a vcf anyway). I will change the command help info to avoid confusion. 

Thanks,

**Comment by die4live** [comment]
@zwdzwd Got it, I've missed the database argument! And all mutation info come back with database set.

Thanks!
