### ISSUE TITLE
what's the difference between gDNA and left_align_gDNA

### ISSUE THREAD

**Issue by die4live** [zwdzwd/transvar#8]
From `canno` results, I noticed that mostly the gDNA position in `region` column is different from the 'left_align_gDNA' in `info`. But I didn't find more information about this.

And furthermore, there are 'unaligned_gDNA'. These concepts confuse a newbie in Bioinformatics like me, and would you please provide some definition or reference?

Thanks!

**Comment by zwdzwd** [comment]
tag like `left_align_gDNA` and `unaligned_gDNA` only appear in the deletion and insertion annotation. They are informative since indels represented in different alignment conventions are equivalent. See for example http://genome.sph.umich.edu/wiki/Variant_Normalization
the left alignment section. I have fleshed out the doc a bit to mirror the use of these tags.

Thanks,
